channels:
- conda-forge
dependencies:
- python=3.9.16
- pip<=22.2.2
- pip:
  - mlflow==2.4
  - catboost==1.0.6
  - cloudpickle==2.2.1
  - ipywidgets==8.0.7
  - numpy==1.24.3
  - pandas==1.5.0
  - scikit-learn==1.0.2
  - scipy==1.9.0
name: mlflow-env
