channels:
- conda-forge
dependencies:
- python=3.9.16
- pip<=22.2.2
- pip:
  - mlflow==2.5.0
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - graphviz==0.20
  - lightgbm==3.3.2
  - matplotlib==3.7.2
  - numpy==1.24.2
  - packaging==23.1
  - pandas==2.0.0
  - psutil==5.9.1
  - scikit-learn==1.0.2
  - scipy==1.9.0
name: mlflow-env
